FROM ltypriv/connectx_lty:new

RUN pip install --no-cache-dir pyyaml
RUN pip install --no-cache-dir tqdm


COPY train.py /app/train.py
COPY training_config.yaml /app/training_config.yaml
COPY run.sh .
