# Random seed for reproducibility
base_seed: 200194596729459020124053724943

# MCTS parameters
n_simulations: 150
c_puct: 1.8
c_fpu: 0.2
mcts_alpha_std: 1.55
mcts_epsilon: 0.25
noise_threshold: 20


# Self-play parameters
num_self_play_games_per_worker: 5
temperature_init: 1.0
temperature_decay_factor: 0.94
temperature_final: 0.2
temp_decay_steps: 15
num_workers: 16

# Training parameters
batch_size: 512
buffer_size: 35000
num_epochs: 8
learning_rate: 0.00005
warmup_steps_ratio: 0.05
weight_decay: 0.0001
dataloader_num_workers: 1

# Checkpoint parameters
checkpoint_interval: 5
eval_interval: 5
eval_games_per_worker: 3
n_simulations_eval : 90

# Training iterations
num_iterations: 150
